###Raising-pr

## مقدمة
طلب السحب هو طريقة للمساهمين لإرسال تغييرات إلى مشروع يديره الآخرون. ويُقترح إجراء التغييرات ثم يقوم المشرفون على المشروع باستعراضها وربما دمجها. في هذا الدليل، سنمضي معكم عبر خطوات تقديم طلب سحب إلى مستودع العلوم المفتوحة - المجتمع السعودي - العربي/JSquarto في GitHub.

## خطوات
1. ابحث عن ميزة أو خطأ تريد العمل عليه.
2. فورك مستودع Open-Science-Community-Sou-Arabia/JSquarto إلى حساب GitHub الخاص بك.
3. استنساخ المستودع المتشابك على جهازك المحلي.
    
    “`باش
    نسخة git https://github.com/Open-Science-Community-Saudi-Arabia/JSquarto
    ```

4. مزامنة الشوك، لتجنب دمج الصراعات.
    
    “`باش
    git بعد اسبوعي-آرابي/JSquarto 
    Git يجلب أعلى مجرى
    Git سحب الرئيسية
    دفعة git
    ```

5. إنشاء فرع جديد مع اسم المستخدم الخاص بك GitHub كاسم له.
    
    “`باش
    Git الدفع -b <your-github-username>
    ```
ليس إلزامياً تسمية الفرع الجديد باسم مستخدم GitHub الخاص بك، ولكن من الممارسات الجيدة القيام بذلك.

6. قم بإجراء التغييرات الخاصة بك على هذا الفرع الجديد.
7. قم بإجراء التغييرات الخاصة بك مع رسالة التزام واضحة.
    
    “`باش
    git يضاف
    git الالتزام -m "رسالة التزام واضحة وموجزة"
    ```

8. قم بدفع التغييرات الخاصة بك إلى مستودع الشوكات الخاص بك.
    
    “`باش
    دفعة منشأ git <your-github-username>
    ```

9. انتقل إلى مستودع [Open-Science-Community-Saudi-Arabia/JSquarto](https://github.com/Open-Science-Community-Saudi-Arabia/JSquarto) على GitHub، ويجب أن ترى رسالة تقترح إنشاء طلب سحب جديد. انقر عليها.
10. لإثارة كلمة المرور ، اختر قالب "PR" وملأه بالمعلومات المطلوبة. قالب PR هو مجموعة من الأسئلة التي تحتاج إلى الإجابة عليها لجعل من الأسهل على المشرفين مراجعة طلب السحب الخاص بك. يمكنك العثور على قالب PR [here](https://github.com/Open-Science-Community-Saudi-Arabia/JSquarto/blob/main/.github/PUL_REQUEST_TEMPLATE.md)

11. إضافة عنوان ووصف واضحين وموجزين لطلب السحب الخاص بك، وشرح التغييرات التي أجريتها.

12. قم بتقديم طلب السحب الخاص بك، وانتظر المشرفين لمراجعة التغييرات الخاصة بك.

تهانينا! لقد قمت للتو بتقديم طلب سحب إلى مستودع Open-Science-Community-Sou-Arabia/JSquarto
