files:
  - source: /docs/**/*.qmd
    translation: /docs/%two_letters_code%/%original_path%/%original_file_name%
  - source: /docs/**/*.md
    translation: /docs/%two_letters_code%/%original_path%/%original_file_name%
bundles:
  - 4
