files:
  - source: /docs/**/*.qmd
    translation: /translations/%two_letters_code%/%original_path%/%original_file_name%.%two_letters_code%.%file_extension%
    multilingual: 1
  - source: /docs/**/*.md
    translation: /translations/%two_letters_code%/%original_path%/%original_file_name%.%two_letters_code%.%file_extension%
    multilingual: 1
bundles:
  - 4
