files:
  - source: /docs/build/**/*.qmd
    ignore:
      - /docs/build/**/*.%two_letters_code%.*
    translation: /docs/_translations/%two_letters_code%/**/%file_name%.%two_letters_code%.qmd
  - source: /docs/build/**/*.md
    ignore:
      - /docs/build/**/*.%two_letters_code%.*
    translation: /docs/_translations/%two_letters_code%/**/%file_name%.%two_letters_code%.md
bundles:
  - 4
