project:
  type: book
  output-dir: _book
book:
  title: Open Innovation Platform Documentation
  chapters:
    - index.md
    - part: Tutorials
      chapters:
        - chapters/tutorials/contributing/improving_documentation.qmd
        - chapters/tutorials/contributing/raising_issues.qmd
        - chapters/tutorials/contributing/raising_pr.qmd
        - chapters/tutorials/how_to/adding_tutorials.qmd
        - chapters/tutorials/how_to/optimizing_workflow.qmd
        - chapters/tutorials/how_to/starting_the_project.qmd
        - chapters/tutorials/project_structure.qmd
        - chapters/tutorials/environment_setup.qmd
        - chapters/tutorials/changelog.qmd
        - chapters/tutorials/localization.qmd
    - part: Globals
      chapters:
        - chapters/globals/globals.qmd
    - part: Utilities
      chapters:
        - chapters/functional doc/utilities/constructidentifier.qmd
        - chapters/functional doc/utilities/commentsutil.qmd
        - chapters/functional doc/utilities/components.qmd
        - chapters/functional doc/utilities/file.qmd
        - chapters/functional doc/utilities/logger.qmd
        - chapters/functional doc/utilities/parser.qmd
        - chapters/functional doc/utilities/writer.qmd
format:
  html:
    theme: cosmo
    highlight: github
    toc: true
    number-sections: false
