# الكاتب

هذه الوحدة النمطية النصية (الكتاب) تحتوي على فئات ووظائف
   لتوليد هيكل الوثائق ومحتواها.
   يتفاعل مع مختلف الملفات والدلائل لتنظيم
   فصول التوثيق، وكتابة المحتوى إلى ملفات markdown ،
   و أنشئ إعداد quarto yaml لكتاب الوثائق.
 
   ملاحظة: هذه الوحدة النمطية لم تكتمل بعد ولا تزال قيد التطوير.



## _أ 
`[متغير]`
 


## غير معروف 
`[other]`
 
**وصف:**
تنسيقات أسماء الملفات عن طريق إزالة جميع الشرطات السفلية `(_)`
    



## غير معروف 
`[other]`
 
**وصف:**
هذه الطريقة تولد ملف تكوين Quarto YAML استنادًا إلى الفصول المقدمة.



## _أ 
`[متغير]`
 
**وصف:**
إنشاء وحدات وتصنيفات من تكوين الدروس, هذه ستكون مطلوبة لكتابتها كفصول في ملف Quarto.yml
     
      



## غير معروف 
`[function]`
 
**وصف:**
ينسخ محتوى الدروس في `/tutorials` إلى `/docs/chapters/tutorials`
     
      



## وحدة 
`[متغير]`
 
**وصف:**
تكتب هذه الطريقة محتوى التوثيق للوحدة النمطية على مسار ملف محدد.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> خيارات <unk> كائن يحتوي على الوحدة ومسار الوجهة. |
<unk> خيارات.destinationPath <unk> مسار الوجهة حيث سيتم كتابة الوثائق. |



## فئات 
`[متغير]`
 
**وصف:**
وتعد هذه الطريقة هيكل الدليل للوثائق من خلال إنشاء المجلدات والملفات اللازمة.



## فئات 
`[متغير]`
 
**وصف:**
هذه الطريقة تكتب الوثائق لكل فئة في ملف مناظر داخل دليل الوثائق.



## غير معروف 
`[function]`
 
**وصف:**
هذه الطريقة تقرأ من خلال مجلد الدروس وتنسخها إلى مجلد الوجهة `/docs` أيضًا
      تتبع بنية الدروس التي تم تعيينها من قبل `config.json' في مجلد الدروس إن وجدت.
     
      



## غير معروف 
`[function]`
 
**وصف:**
تضيف هذه الطريقة الدروس كفصول في ملف _quarto.yml
     
      



## configToAdd 
`[متغير]`
 
**وصف:**
تضيف هذه الطريقة الدروس كفصول في ملف _quarto.yml
     
      



## docsFolderPath 
`[متغير]`
 
**وصف:**
هذه الطريقة تنشئ نسخة من كل ملف qmd في مجلد مستندات لكل لغة

