###بدء المشروع

### بدء بيئة المشروع

قبل البدء، تأكد من تثبيت ما يلي على جهازك:
- [Quarto](https://quarto.org/docs/get-started/index.html)
- [Node.js](https://nodejs.org/en/download/)
- [Yarn](https://yarnpkg.com/getting-started/install) A و [NPM](https://www.npmjs.com/get-npm)
- [Typescript](https://www.typescriptlang.org/download) (اختياري - فقط إذا كانت الملفات التي تعمل معها موجودة في النص النصي


### خطوات
1. إعداد البيئة
    الرجوع إلى دليل إعداد البيئة لمزيد من التفاصيل [انظر هنا](#environment-setup)

2. في الحالات التي تعمل فيها مع مشروع يستخدم الكتابة، سوف تحتاج إلى تجميع ملفات الكتابة إلى جافا سكريبت. للقيام بذلك، قم بتشغيل الأمر التالي في المحطة الطرفية:
    “`باش
    tsc -b 
    ```
    
    تأكد من توجيه الملفات المنقولة إلى الدليل الصحيح. يمكنك القيام بذلك عن طريق تحديث ملف 'tsconfig.json' ليشمل خاصية 'outDir'. وعلى سبيل المثال:
    ```json
    {
        "compilerOptions": {
            "outDir": "./dist"
        }
    }
    ```

3. بدء المشروع
    “`باش
    تشغيل بناء يارن
    ```

    أو 

    “`باش
    npm تشغيل البناء
    ```

    سيولد هذا الأمر التوثيق وسيبدأ أيضًا خادم محلي. يمكنك الوصول إلى الوثائق عن طريق زيارة الرابط الهاتفي المعروض على المحطة الطرفية الخاصة بك.

4. إجراء تغييرات على التوثيق ومشاهدة التغييرات تعكس على المتصفح.

5. بمجرد الانتهاء من ذلك، يمكنك إيقاف الخادم بالضغط على 'Ctrl + C` في المحطة الطرفية الخاصة بك.

6. لإنشاء الوثائق دون بدء تشغيل الخادم، قم بتشغيل الأمر التالي:
    “`باش
    npm تشغيل doc:generate
    ```

    أو

    “`باش
    #yarn doc:generate
    ```
9: لمعاينة الوثائق دون بدء تشغيل الخادم، قم بتشغيل الأمر التالي:
    “`باش
    npm تشغيل doc:preview
    ```

    أو

    “`باش
    yarn تشغيل doc:preview
    ```

    سيؤدي هذا الأمر إلى بدء تشغيل خادم quarto لمعاينة الوثائق التي تم إنشاؤها بالفعل وفتحها في المتصفح الافتراضي الخاص بك.

8. لتنظيف الوثائق التي تم إنشاؤها، قم بتشغيل الأمر التالي:
    “`باش
    npm تشغيل doc:clean
    ```

    أو

    “`باش
    دفتر يارن:نظيف
    ```

    سيؤدي هذا الأمر إلى حذف ملفات المستندات التي تم إنشاؤها. لاحظ أن هذا الأمر لن يحذف دليل `/tutorials` أو `/source_files أو حيثما يتم تخزين الدروس و source_files. سيتم حذف ملفات المستندات التي تم إنشاؤها فقط.



يمكنك تحديد مسار الملفات المصدر عن طريق تضمين علم `--source` في الأمر. وعلى سبيل المثال:
“`باش
npm y --source=./path/to/source_files
```

أو

“`باش
تشغيل yarn (Automatic Translation)
```

يمكنك أيضا تحديد مسار الدروس عن طريق تضمين علم `--البرنامج التعليمي` في الأمر. وعلى سبيل المثال:
“`باش
npm تشغيل البناء --دروس تعليمية=./path/to/tutorials
```


موجز الأوامر:
- 'npm قيد الإنشاء' - إنشاء الوثائق وبدء خادم محلي للحجر
- 'yarn قيد الإنشاء' - توليد الوثائق وبدء خادم الحجر المحلي
- 'npm run doc:generate' - إنشاء الوثائق دون بدء تشغيل الخادم
- 'yarn run doc:generate' - إنشاء الوثائق دون بدء تشغيل الخادم
- 'npm تشغيل doc:preview' - معاينة الوثائق التي تم إنشاؤها دون بدء تشغيل الخادم
- 'yarn run doc:preview' - معاينة الوثائق التي تم إنشاؤها دون بدء تشغيل الخادم
- 'npm run doc:Cle' - حذف ملفات الوثائق التي تم إنشاؤها
- 'yarn run doc:Cle' - حذف ملفات الوثائق التي تم إنشاؤها

الوسوم
- `--source` - تحديد مسار الملفات المصدر
- `--البرنامج التعليمي` - تحديد مسار الدروس

