# ملف Commentsutil

يوفر هذا الملف فئات مفيدة لتحليل واستخراج المعلومات
  من التعليقات داخل ملفات البرمجة. ويتضمن طرقًا لتحديد و
  استخراج البيانات الوصفية من تعليقات الوحدة (module) وغير الوحدة (non-module)،
  تسهيل المواد المرجعية (documentation) بشكل أفضل وفهم بنيات التعليمات البرمجية
  مثل الوظائف (funcion) والمتغيرات و  الفئات (classes) والوحدات النمطية.



## مسمى الوحدة moduleName 
`[variable]`
 
**الوصف:**
هذه الطريقة تستخرج معلومات كتلة الوحدة النمطية من التعليقات، بما في ذلك اسم الوحدة، والوصف، والفئة، والفئة الفرعية، والربط، والمراجع.

** المعلمات (Params):**

| الاسم | الوصف |
| --- | --- |
| تعليقات | التعليقات لاستخراج معلومات كتلة الوحدة منها. |



## الوصف 
`[variable]`
 
**الوصف:**
تستخرج هذه الطريقة معلومات كتلة أخرى من التعليقات، بما في ذلك الوصف، والمشارجات، والربط، والأمثلة، والإرجاعات، والأخطاء التي ألقيت والمراجع.

** المعلمات (Params):**

| الاسم | الوصف |
| --- | --- |
| تعليقات | التعليقات لاستخراج معلومات كتلة الوحدة منها. |



## محتوى الملف 
`[variable]`
 
**الوصف:**
تسترجع هذه الطريقة التعليقات من ملف المصدر باستخدام Acorn parser.

** المعلمات (Params):**

| الاسم | الوصف |
| --- | --- |
<unk> مصدر الملف <unk> مصدر الملف لاسترداد التعليقات منه. |



## غير معروف 
`[other]`
 
**الوصف:**
يمثل هذا الفصل تعليقا مستخرجا من ملف مصدر.

** المعلمات (Params):**

| الاسم | الوصف |
| --- | --- |
<unk> النص <unk> المحتوى النصي للتعليق. |
<unk> الموقع النهائي <unk> الموقع الأخير للتعليق. |



## مجهول 
`[function]`
 
**الوصف:**
وتحدد هذه الطريقة المعلومات التجميعية للتعليق، بما في ذلك نوع البناء واسمه.

** المعلمات (Params):**

| الاسم | الوصف |
| --- | --- |
<unk> معلومات <unk> المعلومات الأساسية التي يجب تعيينها. |



## غير معروف 
`[other]`
 
**الوصف:**
هذه الطريقة تسترجع معلومات الوحدة النمطية من التعليق باستخدام فئة التعليقات.



## غير معروف 
`[other]`
 
**الوصف:**
هذه الطريقة تسترجع معلومات الوحدة النمطية من التعليق باستخدام فئة التعليقات.

