#تعليقسوتيل

يوفر هذا الملف فئات فائدة لتحليل المعلومات واستخراجها
  من التعليقات داخل ملفات التعليمات البرمجية. ويتضمن طرقًا لتحديد و
  استخراج البيانات الوصفية من تعليقات الوحدة وغير الوحدة،
  تسهيل التوثيق بشكل أفضل وفهم بنيات التعليمات البرمجية
  مثل الوظائف والمتغيرات والفئات والوحدات النمطية.



## اسم وحدة 
`[متغير]`
 
**وصف:**
تستخرج هذه الطريقة معلومات كتلة الوحدة من التعليقات، بما في ذلك اسم الوحدة والوصف والفئة والفئة الفرعية والرابط والمراجع.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> تعليقات <unk> التعليقات لاستخراج معلومات كتلة الوحدة النمطية منها. |



## وصف 
`[متغير]`
 
**وصف:**
تستخرج هذه الطريقة معلومات كتلة أخرى من التعليقات، بما في ذلك الوصف، والمشارجات، والربط، والأمثلة، والإرجاع، والأخطاء التي ألقيت والمراجع.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> تعليقات <unk> التعليقات لاستخراج معلومات كتلة أخرى منها. |



## محتوى الملف 
`[متغير]`
 
**وصف:**
تسترجع هذه الطريقة التعليقات من ملف مصدر باستخدام Acorn parser.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> مصدر الملف <unk> مصدر الملف لاسترداد التعليقات منه. |



## غير معروف 
`[other]`
 
**وصف:**
يمثل هذا الصف تعليقا مستخرجا من ملف مصدر.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> النص <unk> محتوى النص للتعليق. |
<unk> الموقع النهائي <unk> الموقع النهائي للتعليق. |



## غير معروف 
`[function]`
 
**وصف:**
وتحدد هذه الطريقة المعلومات التجميعية للتعليق، بما في ذلك نوع واسم البناء.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> معلومات <unk> معلومات البناء التي يجب تعيينها. |



## غير معروف 
`[other]`
 
**وصف:**
هذه الطريقة تسترجع معلومات الوحدة النمطية من التعليق باستخدام صف التعليقات.



## غير معروف 
`[other]`
 
**وصف:**
تسترجع هذه الطريقة معلومات كتلة أخرى من التعليق باستخدام صف التعليقات.

