# المكونات

يتم استخدام هذه الوحدة لتوليد ملف الـ quarto yml
  



## تصوير رداء yConvertAllStringValuesInObjectToLowerCase 
`[function]`
 
**وصف:**
تحويل جميع قيم السلسلة بشكل متكرر في كائن إلى أحرف صغيرة
  

**أمثلة:**

```جافا سكريبت
const obj = {
    الاسم: "مرحبا بالعالم"،
    الوصف: "هذا وصف"،
    blockInfo: {
    الاسم: "مرحبا بالعالم"،
    الوصف: "هذا وصف"،
    },
    };
    تصوير ConvertAllStringValuesInObjectToLowerCase(obj)؛
    // => {
    // الاسم: 'مرحبا بالعالم',
    // الوصف: "هذا وصف"،
    //   blockInfo: {
    // الاسم: 'مرحبا بالعالم',
    // الوصف: "هذا وصف"،
    //   },
    //   }
```



## غير معروف 
`[other]`
 
**وصف:**
إضافة مستند إلى الوحدة
      

**أمثلة:**

```جافا سكريبت
الوحدة النمطية = وحدة جديدة({ name: 'StringUtil' })؛
      وحدة نمطية = وحدة جديدة ({
        الأصل: 'سلسلة.ts',
        البيانات: {
     
           blockInfo: {
           الاطراف : 'StringUtil',
           الوصف: "يحتوي هذا الفصل على أساليب لمعالجة السلاسل"،
           },
           بناء المعلومات: {
           النوع: 'صنف'،
           الاطراف : 'StringUtil',
           },
           },
           });
           module.addDoc(moduleDoc).
```



## غير معروف 
`[other]`
 
**وصف:**
احصل على المستندات في الوحدة
      

**أمثلة:**

```جافا سكريبت
الوحدة النمطية = وحدة جديدة({ name: 'StringUtil' })؛
      وحدة نمطية = وحدة جديدة ({
       الأصل: 'سلسلة.ts',
       البيانات: {
       blockInfo: {
       الاطراف : 'StringUtil',
       الوصف: "يحتوي هذا الفصل على أساليب لمعالجة السلاسل"،
       },
       بناء المعلومات: {
       النوع: 'صنف'،
       الاطراف : 'StringUtil',
       },
       },
       });
       module.addDoc(moduleDoc).
       module.getDocs();
       // => [ModuleDoc]
```



## غير معروف 
`[other]`
 


## غير معروف 
`[other]`
 
**وصف:**
تعيين مسار الملف المصدر
      



## غير معروف 
`[other]`
 
**وصف:**
إضافة وحدة إلى الفئة الفرعية
     
      



## غير معروف 
`[other]`
 
**وصف:**
الحصول على الوحدات في الفئة الفرعية
     
      



## غير معروف 
`[other]`
 
**وصف:**
احصل على اسم الفئة الفرعية
      



## فئة 
`[class]`
 


## غير معروف 
`[other]`
 
**وصف:**
هذا الصف يمثل فئة.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> الاسم <unk> اسم الفئة. |



## غير معروف 
`[other]`
 
**وصف:**
يضيف فئة فرعية إلى الفئة.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> الفئة الفرعية <unk> الفئة الفرعية المراد إضافتها. |



## غير معروف 
`[other]`
 
**وصف:**
يسترجع الفئات الفرعية في الفئة.



## غير معروف 
`[other]`
 
**وصف:**
يسترد اسم الفئة.



## غير معروف 
`[other]`
 
**وصف:**
يضيف وحدة إلى الفئة.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> الوحدة النمطية <unk> الوحدة المراد إضافتها. |



## غير معروف 
`[other]`
 
**وصف:**
يسترجع الوحدات النمطية في الفئة.

