# المكونات

يتم استخدام هذه الوحدة لإنشاء ملف الـ quarto yml
  



## متكررًا 
`[function]`
 
**وصف:**
تحويل جميع قيم السلسلة بشكل متكرر في الكائن إلى أحرف صغيرة
  

* أمثلة: **

```javascript
const obj = {
    name: 'Hello World',
    description: 'This is a description',
    blockInfo: {
    name: 'Hello World',
    description: 'This is a description',
    },
    };
    recursivelyConvertAllStringValuesInObjectToLowerCase(obj);
    // => {
    //   name: 'hello world',
    //   description: 'this is a description',
    //   blockInfo: {
    //   name: 'hello world',
    //   description: 'this is a description',
    //   },
    //   }
```



## مجهول 
`[other]`
 
**وصف:**
إضافة مستند إلى الوحدة النمطية
      

* أمثلة: **

```javascript
const module = new Module({ name: 'StringUtil' });
      const moduleDoc = new ModuleDoc({
        originalFilePath: 'string.ts',
        data: {
     
           blockInfo: {
           name: 'StringUtil',
           description: 'This class contains methods for manipulating strings',
           },
           constructInfo: {
           type: 'class',
           name: 'StringUtil',
           },
           },
           });
           module.addDoc(moduleDoc);
```



## غير معروف 
`[other]`
 
**الوصف:**
إضافة مستند إلى الوحدة النمطية
      

**أمثلة:**

```javascript
const module = new Module({ name: 'StringUtil' });
      const moduleDoc = new ModuleDoc({
       originalFilePath: 'string.ts',
       البيانات: {
       blockInfo: {
       name: 'StringUtil',
       description: 'This class contains methods for manipulating strings',
       },
       بناء المعلومات: {
       النوع: 'صنف'،
       الاسم: 'StringUtil',
       },
       },
       });
       module.addDoc(moduleDoc)؛
       module.getDocs();
       // => [ModuleDoc]
```



## غير معروف 
`[other]`
 


## غير معروف 
`[other]`
 
**الوصف:**
تعيين مسار ملف المصدر
      



## غير معروف 
`[other]`
 
**وصف:**
إضافة وحدة نمطية إلى الفئة الفرعية
     
      



## غير معروف 
`[other]`
 
**وصف:**
إضافة وحدة نمطية إلى الفئة الفرعية
     
      



## غير معروف 
`[other]`
 
**وصف:**
إضافة وحدة نمطية إلى الفئة الفرعية
      



## فئات 
`[class]`
 


## غير معروف 
`[other]`
 
**وصف:**
هذا الصف يمثل فئةً.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
|  إضافة وحدة نمطية إلى الفئة الفرعية. |



## غير معروف 
`[other]`
 
**وصف:**
يضيف فئة فرعية إلى التصنيف.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> الفئة الفرعية <unk> الفئة الفرعية التي يراد إضافتها. |



## غير معروف 
`[other]`
 
**وصف:**
يسترد الفئات الفرعية في الفئة.



## غير معروف 
`[other]`
 
**وصف:**
إضافة وحدة نمطية إلى الفئة الفرعية.



## غير معروف 
`[other]`
 
**وصف:**
إضافة وحدة نمطية إلى الفئة الفرعية.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> الوحدة النمطية <unk> الوحدة المراد إضافتها. |



## غير معروف 
`[other]`
 
**وصف:**
يسترد الفئات الفرعية في الفئة.

