# معرف البناء

الفصل المسمى بناء، يحتوي على طرق لتحديد أنواع مختلفة من التركيبات البرمجية
  (مثل الدوال والمتغيرات والفصول والوحدات) ضمن سطر من الكود.
  وتساعد هذه الطرق في استخراج وتحديد الأسماء المرتبطة بكل نوع من أنواع البناء.



## معرف البناء 
`[class]`
 


## غير معروف 
`[function]`
 
**وصف:**
يسترد اسم بناء الوحدة من سطر معين من التعليمات البرمجية.
     
      

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> السطر <unk> سطر من التعليمات البرمجية إلى التحليل. |



## variableX 
`[function]`
 
**وصف:**
يسترد اسم بناء الوحدة من سطر معين من التعليمات البرمجية.
     
      

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> السطر <unk> سطر من التعليمات البرمجية إلى التحليل. |



## متغير ريجكس 
`[متغير]`
 
** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> السطر <unk> سطر التعليمات البرمجية إلى التحليل. |



## classRegex 
`[متغير]`
 
**وصف:**
يسترد اسم بناء الوحدة من سطر معين من التعليمات البرمجية.
     
      

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> السطر <unk> سطر من التعليمات البرمجية إلى التحليل. |



## إعلان 
`[function]`
 
**وصف:**
يحدد نوع البناء (الدالة، المتغير، الصف، الوحدة، أخرى) من نص الكود المعين.
     
      

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> النص <unk> نص التعليمات البرمجية لتحليله. |



## غير معروف 
`[function]`
 
**وصف:**
يسترد اسم بناء الوحدة من سطر معين من التعليمات البرمجية.
     
      

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> النص <unk> نص التعليمات البرمجية لتحليله. |

