# معرف البناء

الفصل المسمى بناء، يحتوي على طرق لتحديد أنواع مختلفة من التركيبات البرمجية
  (مثل الدوال والمتغيرات والفصول والوحدات) ضمن سطر من الكود.
  وتساعد هذه الأساليب في استخراج وتحديد الأسماء المرتبطة بكل نوع من أنواع البناء.



## معرف البناء 
`[class]`
 


## غير معروف 
`[function]`
 
**وصف:**
يسترجع اسم وحدة بناء من سطر معين من التعليمات البرمجية.
     
      

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> السطر <unk> سطر التعليمات البرمجية إلى التحليل. |



## variableX 
`[function]`
 
**وصف:**
يسترجع اسم بناء الدالة من سطر معين من الكود.
     
      

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> السطر <unk> سطر التعليمات البرمجية إلى التحليل. |



## متغير ريجكس 
`[متغير]`
 
** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> السطر <unk> سطر التعليمات البرمجية إلى التحليل. |



## classRegex 
`[متغير]`
 
**وصف:**
يسترجع اسم بناء الصف الدراسي من سطر معين من الكود.
     
      

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> السطر <unk> سطر التعليمات البرمجية إلى التحليل. |



## إعلان 
`[function]`
 
**وصف:**
يحدد نوع البناء (الدالة، المتغير، الصف، الوحدة، أخرى) من نص الرمز المحدد.
     
      

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> النص <unk> النص البرمجي لتحليله. |



## غير معروف 
`[function]`
 
**وصف:**
يسترجع اسم البناء من نص الكود المعين.
     
      

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> النص <unk> النص البرمجي لتحليله. |

