# Parser

هذا الملف مسؤول عن تحليل التعليقات في ملفات الرموز.
  وهي تستخرج أجزاء مختلفة من المعلومات مثل
  الوصف، الفئة، الفئة الفرعية، الارتباط، المعلمات، قيم الإرجاع،
  ورمي أخطاء من التعليقات باستخدام التعبيرات العادية.



## وصف المطابقة 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج الوصف من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getDescription(تعليق) => 'هذه الطريقة سوف تستخرج الوصف من كتلة التعليقات'
```



## فئة المطابقات 
`[متغير]`
 
**وصف:**
سوف تستخرج هذه الطريقة الفئة من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getCategory(تعليق) => 'StringUtil'
```



## subCategoryRegex 
`[متغير]`
 
**وصف:**
سوف تستخرج هذه الطريقة الفئة من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getSubcategorory(تعليق) => 'StringUtil'
```



## رابط Regex 
`[متغير]`
 
**وصف:**
سوف تستخرج هذه الطريقة الفئة من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getLink(تعليق) => 'StringUtil'
```



## paramsRegex 
`[متغير]`
 
**وصف:**
سوف تستخرج هذه الطريقة الفئة من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getParams(comment) => [{name: 'str', type: 'string', description: 'The string to convert to camel case'}]
```



## moduleRegex 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج اسم الوحدة من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getModuleName(تعليق) => 'StringUtil'
```



## عمليات الإرجاع 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج المردود من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getReturnsValues(تعليق) => [{type: 'string', description: 'The string to convert to camel case'}]
```



## exampleRegex 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج الأمثلة من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getExamples(comment) => ['StringUtil.convertToCamelCase(\'hello world\') => \'helloWorld\'']
```



## الرماة 
`[متغير]`
 
**وصف:**
سوف تستخرج هذه الطريقة الفئة من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getThrownErrors(comment) => [{type: 'Error', description: 'The string to convert to camel case'}]
```



## مراجع Regex 
`[متغير]`
 
**وصف:**
سوف تستخرج هذه الطريقة الفئة من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getReferences(comment) => [{text: 'StringUtil', type: 'localModule'}]
```

