# Parser

هذا الملف مسؤول عن تحليل التعليقات في ملفات التعليمات البرمجية.
  وهي تستخرج أجزاء مختلفة من المعلومات مثل
  وصف الفئة، الفئة الفرعية، الرابط، المعلمات، قيم الإرجاع،
  و ألقى أخطاء من التعليقات باستخدام التعبيرات العادية.



## وصف المطابقة 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج الوصف من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getDescription(تعليق) => "هذه الطريقة سوف تستخرج الوصف من كتلة التعليقات"
```



## فئة المطابقات 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج الفئة من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getcategorory(تعليق) => 'StringUtil'
```



## subCategoryRegex 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج الفئة الفرعية من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getSubcategorory(تعليق) => 'StringUtil'
```



## رابط Regex 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج الرابط من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getLink(تعليق) => 'StringUtil'
```



## paramsRegex 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج كل البارام من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getParams(تعليق) => [{name: 'str', type: 'string', description: 'The string to convert to camel case'}]
```



## moduleRegex 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج اسم الوحدة من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getModuleName(تعليق) => 'StringUtil'
```



## عمليات الإرجاع 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج المردود من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getReturnsValues(تعليق) => [{type: 'string', description: 'The string to convert to camel case'}]
```



## exampleRegex 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج الأمثلة من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getexamples(comy) => ['StringUtil.convertToCamelCase(\'hello world\') => \'helloWorld\']
```



## الرماة 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج الأخطاء الملقاة من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getThrownErrors(تعليم) => [{type: 'Error', description: 'The string to convert to camel case'}]
```



## مراجع Regex 
`[متغير]`
 
**وصف:**
هذه الطريقة سوف تستخرج المراجع من كتلة التعليقات
      

**أمثلة:**

```جافا سكريبت
Parser.getReferences(تعليق) =[{text: 'StringUtil', type: 'localModule'}]
```

