# كاتب

هذه الوحدة النصية النصية (كاتب) تحتوي على فئات ووظائف
   لتوليد هيكل الوثائق ومحتواها.
   يتفاعل مع مختلف الملفات والدلائل لتنظيم
   فصول التوثيق، وكتابة المحتوى إلى ملفات markdown،
   و إنشاء إعداد quarto yaml لكتاب الوثائق.
 
   ملاحظة: هذه الوحدة لم تكتمل بعد ولا تزال قيد التطوير.



## _أ 
`[متغير]`
 


## غير معروف 
`[other]`
 
**وصف:**
تنسيق أسماء الملفات عن طريق إزالة جميع الشرطات السفلية `(_)`
    



## غير معروف 
`[other]`
 
**وصف:**
هذه الطريقة تولد ملف تكوين Quarto YAML استنادًا إلى الفصول المقدمة.



## _أ 
`[متغير]`
 
**وصف:**
إنشاء وحدات وتصنيفات من تكوين الدروس, هذه ستكون مطلوبة لكتابتها كفصول في ملف quarto.yml
     
      



## غير معروف 
`[function]`
 
**وصف:**
نسخ محتوى الدروس في `/tutorials` إلى `/docs/chapters/tutorials`
     
      



## وحدة 
`[متغير]`
 
**وصف:**
تكتب هذه الطريقة محتوى التوثيق لوحدة إلى مسار ملف محدد.

** المعلمات (Params):**

<unk> الاسم <unk> الوصف <unk>
| --- | --- |
<unk> خيارات <unk> كائن يحتوي على الوحدة ومسار الوجهة. |
<unk> خيارات.destinationPath <unk> مسار الوجهة حيث سيتم كتابة الوثائق. |



## فئات 
`[متغير]`
 
**وصف:**
وتعد هذه الطريقة هيكل الدليل للوثائق عن طريق إنشاء المجلدات والملفات اللازمة.



## فئات 
`[متغير]`
 
**وصف:**
هذه الطريقة تكتب الوثائق لكل فئة في ملف مناظر داخل دليل الوثائق.



## غير معروف 
`[function]`
 
**وصف:**
هذه الطريقة تقرأ من خلال مجلد الدروس وتنسخها إلى مجلد الوجهة '/docs` أيضًا
      تتبع بنية الدروس التي تم تعيينها من قبل `config.json' في مجلد الدروس إن وجدت.
     
      



## غير معروف 
`[function]`
 
**وصف:**
هذه الطريقة تضيف الدروس كفصول في ملف _quarto.yml
     
      



## configToAdd 
`[متغير]`
 
**وصف:**
هذه الطريقة تضيف مواصفات اللغة إلى ملف _quarto.yml
     
      



## docsFolderPath 
`[متغير]`
 
**وصف:**
هذه الطريقة تنشئ نسخة من كل ملف qmd في مجلد المستندات لكل لغة

