# Globals

الإنشاءات العالمية



## getJSFilesFromDirectory 
`[function]`
 
**وصف:**
هذه الوظيفة تتعقب بشكل متكرر الدليل المحدد ودلائله الفرعية للعثور على ملفات جافا سكريبت (.js).
  يبدأ بالتحقق من كل عنصر في الدليل. إذا كان البند دليل ، فإنه يتكرر الاتصال بنفسه
  للبحث عن ملفات جافا سكريبت داخل ذلك الدليل. إذا كان العنصر ملف جافا سكريبت ، فإنه يضيف مسار الملف
  إلى مجموعة من ملفات جافا سكريبت التي تم العثور عليها.
 
  



## بداية 
`[function]`
 
**وصف:**
يبدأ عملية توليد الوثائق.
 
  وتبدأ هذه الوظيفة عملية توليد الوثائق عن طريق القيام بالخطوات التالية:
 
  1. يبحث عن ملفات جافا سكريبت في الدليل المحدد والدلائل الفرعية الخاصة به.
  2. يقارن التعليقات من كل ملف من ملفات JavaScript باستخدام `CommentsUtil.getCommentsFromFile()`.
  3. وهو يجهز التعليقات لاستخراج المعلومات النموذجية ويستكمل هياكل بيانات الوحدة وفئاتها وفقا لذلك.
  4. إذا تم تعريف الوحدة الافتراضية، فإنها تضيف الوحدة ومستنداتها إلى الفئة المناسبة أو الفئة الافتراضية.
  5. يقوم بإنشاء دليل الوثائق والملفات باستخدام أداة "الكتاب".
  6. وأخيرا، يسجل التقرير رسالة تشير إلى أن عملية توليد الوثائق قد اكتملت.
 
  تعمل هذه الوظيفة كنقطة دخول لتوليد الوثائق لملفات جافا سكريبت.
 
  



## غير معروف 
`[other]`
 
**وصف:**
هذه الطريقة ستقوم بتحويل سلسلة إلى جمال toUpperCase
      

**أمثلة:**

```جافا سكريبت
StringUtil.convertToCamelCase('hello world') => 'helloWorld'
      StringUtil.convertToCamelCase('hello-world') => 'helloWorld'
      StringUtil.convertToCamelCase('hello_world') => 'helloWorld'
      StringUtil.convertToCamelCase('helloWorld') => 'helloWorld'
      StringUtil.convertToCamelCase('hello') => 'hello'
```



## غير معروف 
`[other]`
 
**وصف:**
هذه الطريقة ستقوم بتحويل سلسلة إلى جمال toUpperCase
      

**أمثلة:**

```جافا سكريبت
StringUtil.convertToCamelCase('hello world') => 'helloWorld'
      StringUtil.convertToCamelCase('hello-world') => 'helloWorld'
      StringUtil.convertToCamelCase('hello_world') => 'helloWorld'
      StringUtil.convertToCamelCase('helloWorld') => 'helloWorld'
      StringUtil.convertToCamelCase('hello') => 'hello'
```

