###Starting-the-project

### Starting the project environment

Before you start, make sure you have the following installed on your machine:
- [Quarto](https://quarto.org/docs/get-started/index.html)
- [Node.js](https://nodejs.org/en/download/)
- [Yarn](https://yarnpkg.com/getting-started/install) or [NPM](https://www.npmjs.com/get-npm)
- [Typescript](https://www.typescriptlang.org/download) (optional - Only required if the files you're working with are in typescript)


### Steps
1. Environment Setup
    Refer to environment setup guide for more details [See here](#environment-setup)

2. For cases where you are working with a project that uses typescript, you will need to compile the typescript files to javascript. To do this, run the following command in the terminal:
    ```bash
    tsc -b 
    ```
    
    Make sure to direct the transpiled files to the correct directory. You can do this by updating the `tsconfig.json` file to include the `outDir` property. For example:
    ```json
    {
        "compilerOptions": {
            "outDir": "./dist"
        }
    }
    ```

3. Start the project
    ```bash
    yarn run build
    ```

    OR 

    ```bash
    npm run build
    ```

    This command will command will generate the documentation and also start a local quarto server. You can access the documentation by visiting the http link shown on your terminal.

4. Make changes to the documentation and see the changes reflect on the browser.

5. Once you are done, you can stop the server by pressing `Ctrl + C` on your terminal.

6. To generate the documentation without starting the server, run the following command:
    ```bash
    npm run doc:generate
    ```

    OR

    ```bash
    yarn run doc:generate
    ```
9: To preview the documentation without starting the server, run the following command:
    ```bash
    npm run doc:preview
    ```

    OR

    ```bash
    yarn run doc:preview
    ```

    This command will startup a quarto server to preview the already generated documentation and open it in your default browser.

8. To clean the generated documentation, run the following command:
    ```bash
    npm run doc:clean
    ```

    OR

    ```bash
    yarn run doc:clean
    ```

    This command will delete the generated documentation files. Note that this command will not delete the `/tutorials` or `/source_files directory or wherever the tutorials and source_files are stored. Only the generated documentation files will be deleted.



You can specify the source files path by including the `--source` flag in the command. For example:
```bash
npm run build --source=./path/to/source_files
```

OR

```bash
yarn run build --source=./path/to/source_files
```

You can also specify the tutorials path by including the `--tutorial` flag in the command. For example:
```bash
npm run build --tutorials=./path/to/tutorials
```


Summary of commands:
- `npm run build` - Generate the documentation and start a local quarto server
- `yarn run build` - Generate the documentation and start a local quarto server
- `npm run doc:generate` - Generate the documentation without starting the server
- `yarn run doc:generate` - Generate the documentation without starting the server
- `npm run doc:preview` - Preview the generated documentation without starting the server
- `yarn run doc:preview` - Preview the generated documentation without starting the server
- `npm run doc:clean` - Delete the generated documentation files
- `yarn run doc:clean` - Delete the generated documentation files

Tags
- `--source` - Specify the source files path
- `--tutorial` - Specify the tutorials path

