###Raising-pr

## مقدمة
طلب السحب هو طريقة للمساهمين لإرسال تغييرات إلى مشروع يديره الآخرون. ويُقترح إجراء التغييرات ثم يقوم المشرفون على المشروع باستعراضها وربما دمجها. في هذا الدليل، سنمضي معكم عبر خطوات تقديم طلب سحب إلى مستودع العلوم المفتوحة - المجتمع السعودي - العربي/JSquarto في GitHub.

## خطوات
1. ابحث عن ميزة أو خطأ تريد العمل عليه.
2. فورك مستودع Open-Science-Community-Sou-Arabia/JSquarto إلى حساب GitHub الخاص بك.
3. استنساخ المستودع المتشابك على جهازك المحلي.
    
    “`باش
    نسخة git https://github.com/Open-Science-Community-Saudi-Arabia/JSquarto
    ```

4. مزامنة الشوك، لتجنب دمج الصراعات.
    
    “`باش
    git بعد إضافة أعلى مسار https://github.com/Open-Science-Community-Saudi-Arabia/JSquarto 
    Git يجلب أعلى مجرى
    Git سحب الرئيسية
    دفعة git
    ```

5. إنشاء فرع جديد مع اسم المستخدم الخاص بك GitHub كاسم له.
    
    “`باش
    Git الدفع -b <your-github-username>
    ```
ليس إلزامياً تسمية الفرع الجديد باسم مستخدم GitHub الخاص بك، ولكن من الممارسات الجيدة القيام بذلك.

6. قم بإجراء التغييرات الخاصة بك على هذا الفرع الجديد.
7. قم بإجراء التغييرات الخاصة بك مع رسالة التزام واضحة.
    
    “`باش
    git يضاف
    git الالتزام -m "رسالة التزام واضحة وموجزة"
    ```

8. قم بدفع التغييرات الخاصة بك إلى مستودع الشوكات الخاص بك.
    
    “`باش
    دفعة منشأ git <your-github-username>
    ```

9. انتقل إلى مستودع [Open-Science-Community-Saudi-Arabia/JSquarto](https://github.com/Open-Science-Community-Saudi-Arabia/JSquarto) على GitHub، ويجب أن ترى رسالة تقترح إنشاء طلب سحب جديد. انقر عليها.
10. لإثارة كلمة المرور ، اختر قالب "PR" وملأه بالمعلومات المطلوبة. قالب PR هو مجموعة من الأسئلة التي تحتاج إلى الإجابة عليها لجعل من الأسهل على المشرفين مراجعة طلب السحب الخاص بك. يمكنك العثور على قالب PR [here](https://github.com/Open-Science-Community-Saudi-Arabia/JSquarto/blob/main/.github/PUL_REQUEST_TEMPLATE.md)

11. إضافة عنوان ووصف واضحين وموجزين لطلب السحب الخاص بك، وشرح التغييرات التي أجريتها.

12. قم بتقديم طلب السحب الخاص بك، وانتظر المشرفين لمراجعة التغييرات الخاصة بك.

تهانينا! لقد قمت للتو بتقديم طلب سحب إلى مستودع Open-Science-Community-Sou-Arabia/JSquarto
