# Globals

الإنشاءات العالمية



## getJSFilesFromDirectory 
`[function]`
 
**وصف:**
هذه الوظيفة تتعقب بشكل متكرر الدليل المحدد ودلائله الفرعية للعثور على ملفات جافا سكريبت (.js).
  يبدأ بالتحقق من كل عنصر في الدليل. إذا كان البند دليل ، فإنه يتكرر الاتصال بنفسه
  للبحث عن ملفات جافا سكريبت داخل ذلك الدليل. إذا كان العنصر ملف جافا سكريبت ، فإنه يضيف مسار الملف
  إلى مجموعة من ملفات جافا سكريبت التي تم العثور عليها.
 
  



## بداية 
`[function]`
 
**وصف:**
يبدأ عملية توليد الوثائق.
 
  وتبدأ هذه الوظيفة عملية توليد الوثائق عن طريق القيام بالخطوات التالية:
 
  1. يبحث عن ملفات جافا سكريبت في الدليل المحدد والدلائل الفرعية الخاصة به.
  2. يقارن التعليقات من كل ملف من ملفات JavaScript باستخدام `CommentsUtil.getCommentsFromFile()`.
  3. وهو يجهز التعليقات لاستخراج المعلومات النموذجية ويستكمل هياكل بيانات الوحدة وفئاتها وفقا لذلك.
  4. إذا تم تعريف الوحدة الافتراضية، فإنها تضيف الوحدة ومستنداتها إلى الفئة المناسبة أو الفئة الافتراضية.
  5. يقوم بإنشاء دليل الوثائق والملفات باستخدام أداة "الكتاب".
  6. وأخيرا، يسجل التقرير رسالة تشير إلى أن عملية توليد الوثائق قد اكتملت.
 
  تعمل هذه الوظيفة كنقطة دخول لتوليد الوثائق لملفات جافا سكريبت.
 
  



## غير معروف 
`[other]`
 
**وصف:**
هذه الطريقة ستقوم بتحويل سلسلة إلى جمال toUpperCase
      

**أمثلة:**

```جافا سكريبت
StringUtil.convertToCamelCase('hello world') => 'helloWorld'
      StringUtil.convertToCamelCase('hello-world') => 'helloWorld'
      StringUtil.convertToCamelCase('hello_world') => 'helloWorld'
      StringUtil.convertToCamelCase('helloWorld') => 'helloWorld'
      StringUtil.convertToCamelCase('hello') => 'hello'
```



## غير معروف 
`[other]`
 
**وصف:**
هذه الطريقة ستقوم بتحويل سلسلة إلى جمال toUpperCase
      

**أمثلة:**

```جافا سكريبت
StringUtil.convertToCamelCase('hello world') => 'helloWorld'
      StringUtil.convertToCamelCase('hello-world') => 'helloWorld'
      StringUtil.convertToCamelCase('hello_world') => 'helloWorld'
      StringUtil.convertToCamelCase('helloWorld') => 'helloWorld'
      StringUtil.convertToCamelCase('hello') => 'hello'
```

