### البيئة_إعداد

---
title: 'إعداد البيئة'
---

#### المتطلبات المسبقة (#environment-setup)
قبل اختبار الأداة محلياً، تأكد من وجود الشروط المسبقة التالية مثبتة على النظام الخاص بك:
- Node.js و npm (مدير الحزمة العقدية)
- Git (اختياري، إذا استنساخ المستودع)

#### التثبيت
لاختبار الأداة محلياً، قم باتباع الخطوات التالية:

1. استنساخ المستودع:
   
   “`باش
   نسخة git https://github.com/Open-Science-Community-Saudi-Arabia/JSquarto
   ```
2. انتقل إلى دليل المشروع

3. تثبيت الإعتمادات 
    
    “`باش
    npm install
    ```

### تشغيل الأداة
بمجرد تثبيت التبعيات ، يمكنك لصق الملفات في ملفات JS أو المجلد في دليل `/source_files` يمكنك تشغيل الأداة باستخدام الأمر التالي
    
1. لإنشاء الوثائق قم بتشغيل الأمر التالي
   
   “`باش
    npm تشغيل doc:generate
   ```

    هذا سوف يستخرج تعليقات JSDoc من ملفات js و يكتبها إلى ملفات Quarto Markdown المقابلة.

    يمكنك اختيار تحديد الدليل حيث 'source_files' ، للقيام بهذا التشغيل 
    
    “`باش
    npm تشغيل doc:generate --source=<path to source files>
    ```

    كما أنه يدعم إضافة دروس مخصصة، للقيام بذلك إضافة ملفات .qmd للدروس في دليل `/tutorials`

    الملفات التي تم إنشاؤها `.qmd` يمكن العثور عليها في مجلد `/docs/chapters`

    قد يختلف هذا الأمر تبعاً لسير العمل الذي تختاره، قد ترغب في إنشاء ملفات المستندات بلغات أخرى أيضاً. للقيام بذلك يمكنك تشغيل الأمر أدناه

    “`باش
    npm تشغيل doc:generate languages=en,ar,es include_localized_versions --source=<path to source files>
    ```

    وسيصدر هذا التقرير الوثائق باللغات الإسبانية والإنكليزية والعربية. يمكنك إضافة المزيد من اللغات عن طريق فصلها بفاصلة. (هذا لا يترجم الوثائق في الواقع، بل يقوم فقط بإنشاء نسخة من الوثائق ويعاد تسميتها إلى اللغة المحددة). للتكامل مع خدمة الترجمة، يمكنك استخدام خدمة [Crowdin](https://crowdin.com/).

    وللحصول على مزيد من المعلومات عن سير العمل المتاح، انظر الدليل هنا @sec-workflow


2. لمعاينة الوثائق التي تم إنشاؤها قيد التشغيل 
    
    “`باش
    npm تشغيل doc:preview
    ```
    
    يتم معاينة المستندات مع quarto، لذا تأكد من تثبيت quarto مسبقاً


3. يمكنك اختيار إنشاء ومعاينة في ذهب واحد، للقيام بهذا تشغيل الأمر أدناه
    
    “`باش
    npm تشغيل البناء --source=<path to source files>
    ```

    سيؤدي هذا إلى إنشاء الوثائق، ومعاينة مع quarto وفتح رابط لمعاينة المستندات
