--- 
 title: Auth Controller 
---

## Description 

 This module contains the controllers for handling user authentication, including login, signup, password reset, super admin activation, and deactivation routes.
 
  The following routes are handled by this module and their corresponding functions: </br>
 
  </br>
  
  <b>POST</b> /auth/login </br>
  <b>POST</b> /auth/signup </br>
  <b>POST</b> /auth/addadmin  </br>
  <b>GET</b> /auth/superadmin/reqactivation/:email </br>
  <b>POST</b> /auth/superadmin/activate  </br>
  <b>GET</b> /auth/superadmin/reqdeactivation/:email  </br>
  <b>POST</b> /auth/superadmin/deactivate </br>
  <b>POST</b> /auth/user/activate/:email </br>
  <b>POST</b> /auth/user/deactivate/:email l </br>
  <b>POST</b> /auth/forgotpassword </br>
  <b>POST</b> /auth/resetpassword </br>
  <b>POST</b> /auth/googlesignin </br>
  <b>GET</b> /auth/github </br>
  <b>GET</b> /auth/github/callback </br>
  <b>POST</b> /auth/google/callback </br>
  <b>GET</b> /auth/verifyemail/:token </br>
   
   
## function user, statusCode, res 
## function handleUnverifiedUser 
## function handleExistingUser 
## function signup 
## function addAdmin 
## function login 
## function verifyEmail 
## function requestSuperAdminAccountActivation 
## function activateSuperAdminAccount 
## function requestSuperAdminAccountDeactivation 
## function deactivateSuperAdminAccount 
## function activateUserAccount 
## function deactivateUserAccount 
## function forgetPassword 
## function resetPassword 
## function googleSignin 
## function getLoggedInUser 
